pipeline: train

embedding_model:
    model: sentence-transformers/all-MiniLM-L6-v2
    batch_size: 20

train:
    feature_pipeline:
        save: True
    modeling_pipeline:
        save: True

eval:
    feature_pipeline:
        save: False
    modeling_pipeline:
        save: False